version: "3"
services:
  app:
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - "db"
  db:
    image: 'mysql'
    restart: 'always'
    ports:
      - "30001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - './backend/scripts:/docker-entrypoint-initdb.d'
  node:
    ports:
      - '3000:3000'
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
      - '/app/node_modules'